version: 2

models:
  - name: stg_customers
    description: stage table for customers
    columns:
      - name: customer_id
        description :  customer identifier
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: if to uniquely identify a customer. 1 customer_unique_code can be mapped to mulitple customer_ids
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: zip code prefix for the customer
      - name: customer_city
        description : customers city
      - name: customer_state
        description : customers state

  - name: stg_orders
    description : contains order information. 1 row for every order  made by the customer
    columns: 
      - name: order_id
        description : unique id to identify an order
        tests:
          - not_null
          - unique
      - name: customer_id
        description: identifier for the customer
        tests: 
          - relationships:
              to: ref('stg_customers')    
              field: customer_id
      - name: order_status
        description: status of the order
      - name: order_purchase_timestamp
        description: the date/timestamp when the order was purchased
      - name: order_approved_at
        description: the time when the order was approved
      - name: order_delivered_carrier_date
        description: time when the order was delivered to the carrier
      - name: order_delivered_customer_date
        description: time when the order was delivered to the customer
      - name: order_estimated_delivery_date
        description: estimated time of delivery of the order
      - name: customer_unique_id
        description: id to uniquely identify a customer
        tests: 
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_unique_id

  - name: stg_order_items
    description: This table contains the list of ordered items along with price and product id
    columns: 
      - name: order_id
        description: unique id to identify an order
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')         
              field: order_id

      - name: order_item_id
        description: a number to identify the ordered item
      - name: product_id
        description: unique id to identify a product
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: seller_id
        description: id to idenifty a seller
      - name: shipping_limit_date
        description: to be filled
      - name: price
        description: price of the item/product sold
        tests: 
          - positive_values
      - name: freight_value
        description: freight value of the product shipped
        tests:
          - positive_values
  
  - name: stg_payments
    description: contains the payment information
    columns: 
      - name: order_id
        description: unique id to identify an order
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')         
              field: order_id
      
      - name: payment_sequential
        description: to be filled
      - name: payment_type
        description : type of the payment
      - name: payment_installments
        description: payment installements
        tests:
          - positive_values
      - name: payment_values
        description: value of the payment
      
  - name: stg_products
    description: contains the product information
    columns:
      - name: product_id
        description: unique identifier for a product
        tests:
          - not_null
          - unique
      - name: product_category_name
        description: category name of the product
      - name: product_name_length
        description: length of product name
      - name: product_description_length
        description: length of product description
      - name: product_photos_qty
        description: to be filled
      - name: product_weight_gm
        description: product weight in grams
        tests:
          - positive_values
      - name: product_length_cm
        description: product length in cm
        tests:
          - positive_values
      - name: product_height_cm
        description: product height in cm
        tests:
          - positive_values
      - name: product_width_cm
        description : product width in cm
        tests: 
          - positive_values