version: 2

models:
  - name: dim_customer
    description: customer dimension table. 1 row for every customer
    columns: 
      - name: customer_unique_id
        description: unique id for the customer
        tests:
          - not_null
          - unique
      - name: num_orders
        description: number of orders made by the customer
      - name: total_orders_value
        description: total order value of the customer
      - name: first_order_date
        description: date when the customer made the first order
      - name: latest_order_date
        description: date when the customer made his latest order      
      - name: most_expensive_order
        description: the most expensive order by the customer aggregated at the order level

  - name: dim_products
    description: product dimension table. 1 record for every product
    columns:
      - name: product_id
        description: unique id for the product
      - name: total_units_sold
        description: total units of the product that is sold
      - name: total_revenue
        description: total revenue for the product
      - name: product_volume
        description: total volume of the product
      - name: flag_top10
        description: flag to indicate if its one of the top 10 products sold based on number of units
      
  - name: fact_daily_product_sales
    description: table with daily products sales data. 1 row for evey day/product combination
    columns:
      - name: product_id
        description: unique id for the product
      - name: date_day
        description: date in yyyy-mm-dd format
      - name: num
        description: number of products sold for the day
    
  - name: fact_sales
    description: this table contains sales info at the order/order_item level
    columns: 
      - name: order_id
        description: unique id for the order
      - name: customer_unique_id
        description: unique id for customer
      - name: order_item_id
        description: id to differentiate the items in an order
      - name: order_type
        description: type of the order
        tests:
          - accepted_values:
              values: ['New','Repeat']
      - name: purchased_delivered_day_diff
        description: number of days between purchased and delivered date
        tests:
          - positive_values
